//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbhishekBlogsDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AbhishekBlogsEntities : DbContext
    {
        public AbhishekBlogsEntities()
            : base("name=AbhishekBlogsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<blog_type> blog_type { get; set; }
        public virtual DbSet<subscribed_user> subscribed_user { get; set; }
        public virtual DbSet<Audit_blogs> Audit_blogs { get; set; }
        public virtual DbSet<blog_keywords> blog_keywords { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
    
        public virtual ObjectResult<GetBlogDetails_Result> GetBlogDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBlogDetails_Result>("GetBlogDetails");
        }
    }
}
