//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbhishekBlogsDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_blogs
    {
        public int Id { get; set; }
        public Nullable<int> log_Id { get; set; }
        public Nullable<int> Blog_type_Id { get; set; }
        public string Blog_Id { get; set; }
        public string Blog_short_Content { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Audit_TimeStamp { get; set; }
        public string Audit_Action { get; set; }
    }
}
