//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbhishekBlogsDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_keywords
    {
        public int Id { get; set; }
        public Nullable<int> Page_Id { get; set; }
        public string Page_Type { get; set; }
        public string Page_Keywords { get; set; }
        public string Page_Description { get; set; }
        public Nullable<System.DateTime> Keyword_CreatedDate { get; set; }
        public Nullable<System.DateTime> Keyword_UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
