//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbhishekBlogsDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Commentdetails { get; set; }
        public int BlogId { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual blog blog { get; set; }
    }
}
