//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbhishekBlogsDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class subscribed_user
    {
        public int Id { get; set; }
        public string User_Name { get; set; }
        public string User_Email { get; set; }
        public string User_Contact { get; set; }
        public string User_Address { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string BlogTypeId { get; set; }
    }
}
